### ISSUE TITLE
Steam Linux Games not working

### ISSUE THREAD

**Issue by 2relativ** [gamer-os/steam-tweaks#14]
Games like Castle Story are not working correctly. Crashing on startup.
In ProtonDB listed as "native". Also Rocket League from Epic Games Store. Also listed as "native". Tested on 2 Systems. One with newer Intel and Intel Graphics, second with older i7 and AMD Radeon.

**Comment by alkazar** [comment]
Oh, I just noticed that Rocket League is being used from Epic Games. EGS games are all run through proton because there are no Linux games on EGS. I have not been able to get the EGS version of Rocket League to work with any version of Proton, unfortunately.

**Comment by alkazar** [comment]
Rocket League from EGS should work now on GamerOS 21. You will have to re-install it if it is already install though.

**Comment by 2relativ** [comment]
Nicely done. May I ask how you solved it? Just curious.

**Comment by alkazar** [comment]
Switched to using latest proton 5.13 for EGS games which fixed Rocket League along with enabling controllers to work.
