### ISSUE TITLE
Shortcuts created by Steam Buddy do not behave like regular games

### ISSUE THREAD

**Issue by rshamsnejad** [gamer-os/steam-tweaks#15]
Games added through Steam Buddy are not shown up in the "Recent" list, and adding them to "Favorites" does not survive a reboot.

I believe the `steam-shortcuts` script is the culprit here.

**Comment by alkazar** [comment]
This is likely because the shortcut file is recreated from scratch every time. Which means any custom tags added to shortcuts through Steam will be erased and that might include membership in the "Recent" list.

**Comment by Samsagax** [comment]
Would be a good logic to not create a new shortcut if the steam I'd doesn't change?
