### ISSUE TITLE
Changes in compat-tool on steam-shortcut.yaml are not honoured

### ISSUE THREAD

**Issue by Samsagax** [gamer-os/steam-tweaks#19]
I'm trying to use a different Proton version for Cyberpunk 2077 GOG version installed by wyvern and innoextract (after an unsuccessful install attempt by steam-buddy, download timed out). 
The game works with the default proton 5.13-5 version provided by Steam as is configured by steam-buddy. I tweaked the file `~/.local/share/steam-shortcuts/steam-buddy.gog.yaml` to match installation folder and the game still works but changing the `compat_tool` attribute from `proton_513` to `Proton-6.1-GE-2` just makes the game use `Proton-5.21-GE-1` instead. That doesn't make sense. Is there a way to change the Proton version in the shortcut yaml file?
I have the folder `$STEAMROOT/compatibilitytools.d/Proton-6.1-GE-2` and it works for other Steam games.

**Comment by alkazar** [comment]
1. How do you know it is using Proton 5.21 GE?
2. After making the change did you restart Steam from Steam Buddy or restart your computer?

**Comment by Samsagax** [comment]
>     1. How do you know it is using Proton 5.21 GE?

Here are the references I found just now trying to run the game:
- In the file .xsession-errors there are a lot of entries trying to apply Proton-5.21-GE-1 protonfixes (corefonts failing mostly).
- MangoHud tries to load conf file from `~/.local/share/Steam/compatibility tools.d/Proton-5.21-GE-1/dist/bin/MangoHud.conf`.
- And finally in game Mangohud shows Proton-5.21-GE-1 as wine version.

>     2. After making the change did you restart Steam from Steam Buddy or restart your computer?

I rebooted my pc several times. Didn't do it from Steam Buddy. But then I tried that and same result, but it triggered the "looking for updates, validating install" steam splash screen.

**Comment by Samsagax** [comment]
Just tested version 0.7.2 and it seems to be fixed. I noticed you added 6.1-GE as compatibility tool in the steam-tweaks package, I think there should be documented how to add our own proton versions. But otherwise I think the issue is resolved and would close it. Thanks for the fast fix
