### ISSUE TITLE
[proton-whitelist] disabling custom steam play settings does not restore proton-whitelist settings

### ISSUE THREAD

**Issue by alkazar** [gamer-os/steam-tweaks#2]
Selecting and then deselecting `Force the use of a specific Steam Play compatibility tool` from within Steam for a game, permanently disables `proton-whitelist` from being able to handle that game in the future.

The expected outcome is that once the option is disabled, the original `proton-whitelist` settings should take effect immediately.

It is likely that Steam continues to maintain some settings for the game even after the option is disabled and that is overriding the `proton-whitelist` settings.

**Comment by DaedalusHyperboreus** [comment]
I've developed a little patch to fix that issue.
What do you think of the following?

--- /usr/bin/steam-config	2020-04-09 00:43:23.000000000 +0200
+++ steam-config.new	2020-04-26 20:59:43.768717156 +0200
@@ -35,6 +35,14 @@

 	if 'CompatToolMapping' not in steam:
 		steam['CompatToolMapping'] = {}
+	else:
+		stale_entries=[]
+		for game in steam['CompatToolMapping']:
+			if not steam['CompatToolMapping'][game]['name'] and not steam['CompatToolMapping'][game]['config']:
+				stale_entries.append(game)
+
+		for entry in stale_entries:
+			del data['InstallConfigStore']['Software']['Valve']['Steam']['CompatToolMapping'][entry]

 	return data
