### ISSUE TITLE
Bioshock Remastered needs `noesync` and `nofsync` passed as variables at launch, `compat_config` variables doesn´t seem to work. 

### ISSUE THREAD

**Issue by Samsagax** [gamer-os/steam-tweaks#23]
Adding options to the `compat_config` variable doesn´t seem to work. I don´t know if other games are affected, but [Bioshock Remastered](https://github.com/gamer-os/steam-tweaks/blob/8f08197bb4414c878831705354448b9de8b95e49/steam-tweaks.yaml#L119-L122) and probably some friends, need to be passed `PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command%` so the textures wont be blurred.
The same `noesync nofsync` options passed through the `compat_config` variable in `steam-tweaks.yaml` doesn´t seem to have an effect as I see the same textures blurred in all the game.

Maybe is safer to set those env variables in the `launch_options` variable inside `steam-tweaks.yaml`

Edit: as a sidenote, `proton_513` seems to work better than `proton_411` performance-wise.

**Comment by alkazar** [comment]
`noesync` is specified and the BioShock games are working for me.

What OS are you using?

**Comment by Samsagax** [comment]
> `noesync` is specified and the BioShock games are working for me.
> 
> What OS are you using?

I'm using Arch Linux with the same packages as GamerOS installed.

**Comment by alkazar** [comment]
Yes, the textures are not blurry for me. Are you perhaps using a custom kernel?
The default setup does not include `nofsync`, only `noesync`.

Did you add `nofsync` and to which file exactly? After you made the change, did you restart Steam? How are you applying the steam tweaks to the Steam config?

**Comment by Samsagax** [comment]
I'm using zen kernel. It has the added futex patches (no futex2 though). I added the `nofsync` to the system-wide `steam-tweaks.yaml` file after the user one didn't do anything. Yes I restarted steam (I rebooted the pc actually) both times. I'm applying all tweaks by means of the steam-tweaks packages and no other fiddling.
The thing I encounter is that those variables in `compat_config` didn't do anything noticeable but the variables in the launch line do.

**Comment by alkazar** [comment]
What was the exact path that you modified the `steam-tweaks.yaml` file at?

When you added the launch parameters, did you do that directly in Steam?

**Comment by Samsagax** [comment]
I found out in the home file `~/.config/steam-tweaks.yaml` I only put those games I want to override the main file `/usr/share/steam-tweaks.yaml` and I was wondering why BioShock tweaks weren't applied. Seems that the `/use/bin/steam-tweaks` script only applies the settings on the user file (that is on home) and tries to copy the main global file to `.local/share/steam-tweaks.yaml` only if the file does not exists. That won't override it if there is an update for the main file. Maybe that one should be skipped completely and use the main file instead?
I'll try to be more specific about my test case and report back. Thanks for your effort and fast response @alkazar

**Comment by alkazar** [comment]
The way it works is:

1. we try to download the latest `steam-tweaks.yaml` file to `~/.local/share/steam-tweaks.yaml`
2. if we could not download `steam-tweaks.yaml` and `~/.local/share/steam-tweaks.yaml` does not exist, we copy it from `/usr/share/steam-tweaks/steam-tweaks.yaml` to `~/.local/share/steam-tweaks.yaml`
3. we load `~/.local/share/steam-tweaks.yaml`
4. we load `~/.config/steam-tweaks.yaml`, overriding any game configs that were already loaded previously

So, that means you should never edit `/usr/share/steam-tweaks/steam-tweaks.yaml` nor `~/.local/share/steam-tweaks.yaml` as indicated in the comment at the top of both files. Any customizations must go in `~/.config/steam-tweaks.yaml`.

It sounds like there isn't a bug in setting `compat_config`, just a misunderstanding of how the configuration works.

I will add `nofsync` for each use of `noesync` in the current configuration which should solve the specific problem with the BioShock games for you and anyone else using a custom kernel.

**Comment by Samsagax** [comment]
@alkazar thanks for clarifying the files mixup.
Still when adding my own `.config/steam-tweaks.yaml` file overriding the game as this
````
"409710": # BioShock Remastered                                                                    compat_tool: proton_411
  compat_config: noesync nofsync                                                                            launch_options: -nointro
````
The game still uses proton 5.13-6 instead of the stated 4.11. And the compat_config options are ignored.

**Comment by alkazar** [comment]
If you have modified the proton settings for the game in Steam, that will take precedent.

To test the `steam-tweaks.yaml` changes, you could delete (or temporarily remove) `~/.local/share/Steam/config/config.vdf` where all the settings are stored.

**Comment by Samsagax** [comment]
Ok. I'm not sure if I changed something so I nuked both `.local/share/steam-tweaks.yaml` and `.local/share/Steam/config/config.vdf` files.
After that I removed BioShock Remastered prefix to star on a clean state.

What I found is that now the config won't start with Proton 4.11 as stated in the tweak file I get a crash after the BioShock splash logo with this at starting steam log:
````
======================
Proton: 1582308386 proton-4.11-13
SteamGameId: 409710
Command: ['/opt/steam/mass_library/SteamLibrary/steamapps/common/BioShock Remastered/Build/Final/BioshockHD.exe', '-nointro']
Options: {'noesync nofsync'}
======================
````
I noticed the option is taken as one. So I created again `.config/steam-tweak.yaml` file and separated those with a comma and no space. The game now has both parameters as separated options but still won't work.
````
======================
Proton: 1582308386 proton-4.11-13
SteamGameId: 409710
Command: ['/opt/steam/mass_library/SteamLibrary/steamapps/common/BioShock Remastered/Build/Final/BioshockHD.exe', '-nointro']
Options: {'nofsync', 'noesync'}
======================
````
So I changed `compat_tool` on my user configuration to.ise Proton 5.13 and the game worked this time and no blurred textures. But I noticed it added a new option `forcelgadd` to the mix.
````
======================
Proton: 1612904805 proton-5.13-6
SteamGameId: 409710
Command: ['/opt/steam/mass_library/SteamLibrary/steamapps/common/BioShock Remastered/Build/Final/BioshockHD.exe', '-nointro']
Options: {'nofsync', 'forcelgadd', 'noesync'}
SteamLinuxRuntime: v0.20210309.0-0-gb38a1fb
pressure-vessel: 0.20210305.0+srt1 scout 0.20210309.0
soldier: 0.20210309.0 soldier 0.20210309.0
======================
````
So again tested with Proton 4.11 and adding that option. The option gets in, but the game still crashes. Maybe is a missing library on my end. So I would stick to Proton 5.13 that works with Steam Runtime Soldier and call it a day.

Here is the configuration that worked for me:
````
"409710": # BioShock Remastered
  compat_tool: proton_513
  compat_config: noesync,nofsync
  launch_options: -nointro
````
So, thank you again for your great efforts in making Linux gaming a little easier for all of us @alkazar. Hope this helps another one.

**Comment by alkazar** [comment]
Thanks for the amazing detective work and your persistence!

I will retest with your settings and update. Thanks so much!

**Comment by Samsagax** [comment]
Thanks @alkazar. Ironically today Valve made it official for BioShock 2 Remastered: https://github.com/ValveSoftware/Proton/releases/tag/proton-6.3-1

**Comment by alkazar** [comment]
I updated the steam-tweaks configuration file. Thanks again!
