### ISSUE TITLE
steam-shortcuts only adds one shortcut per shortcut file

### ISSUE THREAD

**Issue by sharkwouter** [gamer-os/steam-tweaks#4]
I've seen this happen more specifically with shortcut files in '/var/lib/steam-buddy/shortcuts'. This can be observed when adding multiple snes roms through steam-buddy.

**Comment by sharkwouter** [comment]
To add some additional info to this. Only the bottom entry is added to Steam.

**Comment by alkazar** [comment]
Fixed. Thanks!
