### ISSUE TITLE
Feature: fps counter

### ISSUE THREAD

**Issue by ltomes** [gamer-os/steam-tweaks#6]
Since Pacman is not installed in this distro, have you considered including glxosd, or some other tool? Is there a convenient way to enable an fps counter that I'm not aware of?

Thanks for your time

**Comment by alkazar** [comment]
For Vulkan games you can set the game launch option to `MANGOHUD=1 %command%`.The next release of GamerOS (coming very soon) will enable mangohud by default (toggleable from Steam Buddy) and have an updated version with OpenGL support.

**Comment by ltomes** [comment]
@alkazar That was exactly what I was looking for thank you.
I had no idea this feature was in here. I would be happy to update the readme with basic instructions for others. Are there other features like this that are included in steam tweaks but not documented?

**Comment by alkazar** [comment]
This is not really a feature of steam tweaks.

The mangohud integration in steam buddy is not released yet and therefore not documented.

There are some other features coming as well that will be added to the documentation once released.
